#!/usr/bin/env python3

import curses

def main(scr):
	curses.use_default_colors()

	ed = Editor(scr)
	while ed.process_input():
		pass

class Editor:
	def __init__(self, scr):
		self.scr = scr

		self.win = curses.newwin(curses.LINES - 1, curses.COLS, 0, 0)
		scr.addstr(curses.LINES - 1, 0, '[no file]')
		self.cursor = Cursor(scr)
		self.cursor.move()
		scr.refresh()

	def process_input(self):
		k = self.scr.getkey()
		if k == 'Q':
			return False
		elif k == 'h':
			if self.cursor.x > 0:
				self.cursor.x -= 1
				self.cursor.move()
		elif k == 'j':
			if self.cursor.y < curses.LINES - 2:
				self.cursor.y += 1
				self.cursor.move()
		elif k == 'k':
			if self.cursor.y > 0:
				self.cursor.y -= 1
				self.cursor.move()
		elif k == 'l':
			if self.cursor.x < curses.COLS - 1:
				self.cursor.x += 1
				self.cursor.move()
		return True

class Cursor:
	def __init__(self, scr):
		self.scr = scr
		self.y = 0
		self.x = 0

	def move(self):
		self.scr.move(self.y, self.x)

if __name__ == '__main__':
	curses.wrapper(main)
